### ISSUE TITLE
PYWIN32

### ISSUE THREAD

**Issue by ben4361** [muteb/Hoarder#3]
Collecting pywin32 (from -r requirement.txt (line 5))
  ERROR: Could not find a version that satisfies the requirement pywin32 (from -r requirement.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for pywin32 (from -r requirement.txt (line

Can this be used to collect windows artefacts from a Linux host?

**Comment by AbdulRhmanAlfaifi** [comment]
Hello ben,
Unfortunately you can not. We use pywin32 to get the specified partition offset in the physical drive which allows us to copy locked files. However this is a good idea ! we will look into it more

Thank you for the suggestion :)
